### ISSUE TITLE
Worker fails to deserialize code

### ISSUE THREAD

**Issue by ferchault** [NablaChem/hummingqueue#19]
Exception
```Traceback (most recent call last):
  File "/gpfs/home08/0026/uk092940/hmq_prod/envs/envs/hmq_3.9/lib/python3.9/site-packages/rq/worker.py", line 432, in work
    self.execute_job(job, queue)
  File "/gpfs/home08/0026/uk092940/hmq_prod/envs/envs/hmq_3.9/lib/python3.9/site-packages/hmq/hmq.py", line 604, in execute_job
    api.warm_cache(job.kwargs["function"])
  File "/gpfs/home08/0026/uk092940/hmq_prod/envs/envs/hmq_3.9/lib/python3.9/site-packages/hmq/hmq.py", line 375, in warm_cache
    functions[function] = cloudpickle.loads(callable)
AttributeError: Can't get attribute '_function_setstate' on <module 'cloudpickle.cloudpickle' from '/gpfs/home08/0026/uk092940/hmq_prod/envs/envs/hmq_3.9/lib/python3.9/site-packages/cloudpickle/cloudpickle.py'>
```

[PrefectHQ/prefect/issues/5818](https://github.com/PrefectHQ/prefect/issues/5818) suggests that pinning the cloudpickle version might help

**Comment by ferchault** [comment]
Worker had cloudpickle 2.2.1. After upgrade to 3.0.0 (like in the pickler's environment), the error is gone.
