### ISSUE TITLE
Pulling from file fails for fresh import

### ISSUE THREAD

**Issue by ferchault** [NablaChem/hummingqueue#36]
```>>> import hmq
>>> tag = hmq.Tag.from_file("file.tag")
>>> tag.pull()
  2%|████▏                                                                                                                                                                                            | 50/2286 [00:00<00:00, 696728.24it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ferchault/opt/conda/envs/regular/lib/python3.11/site-packages/hmq/hmq.py", line 650, in pull
    self._pull_batch(tasklist)
  File "/home/ferchault/opt/conda/envs/regular/lib/python3.11/site-packages/hmq/hmq.py", line 634, in _pull_batch
    results = api.retrieve_results(tasklist)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ferchault/opt/conda/envs/regular/lib/python3.11/site-packages/hmq/hmq.py", line 343, in retrieve_results
    "challenge": self._get_challenge(),
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ferchault/opt/conda/envs/regular/lib/python3.11/site-packages/hmq/hmq.py", line 523, in _get_challenge
    response = str(self._get("/auth/challenge").json()["challenge"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ferchault/opt/conda/envs/regular/lib/python3.11/site-packages/hmq/hmq.py", line 302, in _get
    response = requests.get(baseurl + endpoint, verify=self._verify)
                            ~~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by ferchault** [comment]
Invalid: was already fixed on latest version. Old installations can work around by calling `hmq.api._build_box()` prior to the pull.
